apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: kpt-cl
build:
  artifacts:
  - image: "frontend"
    context: php-redis
deploy:
  kubectl:
    flags:
      apply:
      - "--prune=true"
      - "--all=true"
      - "--namespace=default"
    manifests:
    - config/frontend/*.yaml
